JAVAC=javac
sources = $(wildcard *.java)
classes = $(sources:.java=.class)
all: $(classes)

%.class : %.java
	$(JAVAC) -sourcepath ./ -cp choco-solver-3.3.4-with-dependencies.jar $<

clean :
	rm -f *.class

